import { StyleSheet } from "react-native";

export const budgetstyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#000",
    padding: 16,
  },
  header: {
    alignItems: "center",
    marginBottom: 24,
    paddingTop: 16,
  },
  logo: {
    color: "#FF3D3D",
    fontSize: 22,
    fontWeight: "bold",
    marginBottom: 8,
  },
  heading: {
    color: "#FFF",
    fontSize: 28,
    fontWeight: "bold",
    marginBottom: 4,
  },
  subheading: {
    color: "#FF3D3D",
    fontSize: 16,
    fontWeight: "500",
    letterSpacing: 1.5,
  },
  budgetSummaryCard: {
    backgroundColor: "#111",
    borderRadius: 16,
    padding: 20,
    marginBottom: 24,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    elevation: 5,
    shadowColor: "#FF3D3D",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    borderWidth: 1,
    borderColor: "#333",
  },
  summaryTextContainer: {
    flex: 1,
  },
  summaryLabel: {
    color: "#AAA",
    fontSize: 14,
    marginBottom: 4,
  },
  summaryAmount: {
    color: "#FFF",
    fontSize: 22,
    fontWeight: "bold",
    marginBottom: 12,
  },
  circularProgressContainer: {
    position: "relative",
    width: 100,
    height: 100,
    alignItems: "center",
    justifyContent: "center",
  },
  circularText: {
    position: "absolute",
    color: "#FFF",
    fontSize: 20,
    fontWeight: "bold",
  },
  circularSubtext: {
    position: "absolute",
    color: "#FF3D3D",
    fontSize: 12,
    top: 65,
  },
  chartCard: {
    backgroundColor: "#111",
    borderRadius: 16,
    padding: 16,
    marginBottom: 24,
    alignItems: "center",
    elevation: 5,
    shadowColor: "#FF3D3D",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    borderWidth: 1,
    borderColor: "#333",
  },
  chartTitle: {
    color: "#FFF",
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 16,
    alignSelf: "flex-start",
  },
  chartContainer: {
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 8,
  },
  legendContainer: {
    marginTop: 8,
    marginBottom: 16,
    paddingHorizontal: 8,
  },
  breakdownTitle: {
    color: "#FFF",
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 16,
  },
  categoryCard: {
    backgroundColor: "#111",
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    elevation: 3,
    shadowColor: "#FF3D3D",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    borderWidth: 1,
    borderColor: "#333",
  },
  categoryHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  categoryIndicator: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginRight: 8,
  },
  categoryLabel: {
    color: "#FFF",
    fontSize: 16,
    fontWeight: "600",
    flex: 1,
  },
  categoryAmount: {
    color: "#FFF",
    fontSize: 16,
    fontWeight: "bold",
  },
  categoryBudget: {
    color: "#AAA",
    fontWeight: "normal",
  },
  progressBarBackground: {
    height: 10,
    backgroundColor: "#333",
    borderRadius: 5,
    overflow: "hidden",
    marginBottom: 8,
  },
  progressBarFill: {
    height: "100%",
    backgroundColor: "#FF3D3D",
  },
  categoryFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 4,
  },
  categoryPercentage: {
    color: "#FF3D3D",
    fontSize: 14,
    fontWeight: "500",
  },
  categoryRemaining: {
    color: "#AAA",
    fontSize: 14,
  },
  editButton: {
    backgroundColor: "#FF3D3D",
    borderRadius: 10,
    paddingVertical: 14,
    paddingHorizontal: 20,
    alignItems: "center",
    marginVertical: 20,
    flexDirection: "row",
    justifyContent: "center",
  },
  editButtonText: {
    color: "#FFF",
    fontSize: 16,
    fontWeight: "bold",
    marginLeft: 8,
  },
  footer: {
    marginTop: 8,
    marginBottom: 32,
    alignItems: "center",
  },
  footerText: {
    color: "#888",
    fontSize: 14,
    fontStyle: "italic",
    marginBottom: 8,
  },
  footerTagline: {
    color: "#FFF",
    fontSize: 14,
    textAlign: "center",
    lineHeight: 20,
  },
});